name: 'Deployment CI'
on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run command on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            set -e;
            cd ${{ secrets.PROJECT_FOLDER }};
            git checkout master;
            git pull;
      - name: Dispatch Event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ secrets.GIT_HOOK_URL }} \
            -d '{"event_type": "dispatch-event"}'
